### ISSUE TITLE
RedirectRepository does not extends \TYPO3\CMS\Extbase\Persistence\Repository

### ISSUE THREAD

**Issue by hoermannklaus** [patrickbroens/TYPO3.UrlForwarding#24]
I wanted to delete all Redirects on a certain page. I thought of creating a new RedirectRepository on which I could call all the possible actions for a Repository.

Now I see, that this repo does not extend the Persistence Repository in TYPO3 CMS Extbase. 

Wouldnt this be a quite good idea, to do so?

Thanks

**Comment by patrickbroens** [comment]
The reason why Extbase is not involved in this extension is performance. Bootstrapping Extbase is not a good idea for this, since it is called on each page request.

PS: In TYPO3 version 9 you do not need this extension anymore, since it is part of the core.
